name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build
      run: make

    - name: Test
      run: |
        # Define the test inputs
        inputs=(
          "1 2 3 4"
          "4 3 2 1"
          "2 1"
          "1 2"
          "3 1 4 2"
          "2 1 3"
          "1 2 3"
          "4 3 1 2"
          "$(seq 1 100 | shuf | tr '\n' ' ')"
        )
        
        # Test each input
        for input in "${inputs[@]}"; do
          output=$(./push_swap $input)
          
          # Check if the output is in the expected format and the numbers are sorted correctly
          sorted=$(echo "$input" | tr ' ' '\n' | sort -n | tr '\n' ' ')
          if ! echo "$output" | grep -q "stack: \[.*\]$"; then
            echo "Output format is not correct for input '$input':"
            echo "Expected format: 'stack: $sorted' with the numbers sorted correctly"
            echo "Actual output: $output"
            exit 1
        fi
        done
